# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default=b'', max_length=100)),
                ('path', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
