# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0004_auto_20160101_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='extension',
            field=models.CharField(default='Epub', max_length=100),
            preserve_default=False,
        ),
    ]
