# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0005_book_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default=b'Unknown Author', max_length=100),
        ),
    ]
